var x = 4;
var y = -x;
console.log("value of x: ", x);
console.log("value of y: ", y);
var msg = "hello" + "world";
console.log(msg);
var num = -2;
var result = num > 0 ? "positive" : "non-positive";
console.log(result);
var nume = 12;
console.log(typeof nume);
